/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardPostsRouteRouteImport } from './routes/_dashboard/posts/route'
import { Route as DashboardConstantsRouteRouteImport } from './routes/_dashboard/constants/route'
import { Route as DashboardAboutRouteRouteImport } from './routes/_dashboard/about/route'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/_dashboard/products/index'
import { Route as DashboardPostsIndexRouteImport } from './routes/_dashboard/posts/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/_dashboard/orders/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/_dashboard/categories/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/_dashboard/analytics/index'
import { Route as DashboardAboutIndexRouteImport } from './routes/_dashboard/about/index'
import { Route as DashboardUsersIdRouteRouteImport } from './routes/_dashboard/users/$id/route'
import { Route as DashboardProductsOrderRouteRouteImport } from './routes/_dashboard/products/order/route'
import { Route as DashboardProductsNewRouteRouteImport } from './routes/_dashboard/products/new/route'
import { Route as DashboardPostsPostIdRouteRouteImport } from './routes/_dashboard/posts/$postId/route'
import { Route as DashboardOrdersIdRouteRouteImport } from './routes/_dashboard/orders/$id/route'
import { Route as DashboardCategoriesOrderRouteRouteImport } from './routes/_dashboard/categories/order/route'
import { Route as DashboardCategoriesNewRouteRouteImport } from './routes/_dashboard/categories/new/route'
import { Route as DashboardPostsPostIdIndexRouteImport } from './routes/_dashboard/posts/$postId/index'
import { Route as DashboardProductsIdEditRouteRouteImport } from './routes/_dashboard/products/$id/edit/route'
import { Route as DashboardCategoriesIdEditRouteRouteImport } from './routes/_dashboard/categories/$id/edit/route'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsRouteRoute = DashboardPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConstantsRouteRoute = DashboardConstantsRouteRouteImport.update({
  id: '/constants',
  path: '/constants',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAboutRouteRoute = DashboardAboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPostsRouteRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAboutIndexRoute = DashboardAboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAboutRouteRoute,
} as any)
const DashboardUsersIdRouteRoute = DashboardUsersIdRouteRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsOrderRouteRoute =
  DashboardProductsOrderRouteRouteImport.update({
    id: '/products/order',
    path: '/products/order',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsNewRouteRoute =
  DashboardProductsNewRouteRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPostsPostIdRouteRoute =
  DashboardPostsPostIdRouteRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => DashboardPostsRouteRoute,
  } as any)
const DashboardOrdersIdRouteRoute = DashboardOrdersIdRouteRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesOrderRouteRoute =
  DashboardCategoriesOrderRouteRouteImport.update({
    id: '/categories/order',
    path: '/categories/order',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCategoriesNewRouteRoute =
  DashboardCategoriesNewRouteRouteImport.update({
    id: '/categories/new',
    path: '/categories/new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPostsPostIdIndexRoute =
  DashboardPostsPostIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPostsPostIdRouteRoute,
  } as any)
const DashboardProductsIdEditRouteRoute =
  DashboardProductsIdEditRouteRouteImport.update({
    id: '/products/$id/edit',
    path: '/products/$id/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCategoriesIdEditRouteRoute =
  DashboardCategoriesIdEditRouteRouteImport.update({
    id: '/categories/$id/edit',
    path: '/categories/$id/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof DashboardAboutRouteRouteWithChildren
  '/constants': typeof DashboardConstantsRouteRoute
  '/posts': typeof DashboardPostsRouteRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/categories/new': typeof DashboardCategoriesNewRouteRoute
  '/categories/order': typeof DashboardCategoriesOrderRouteRoute
  '/orders/$id': typeof DashboardOrdersIdRouteRoute
  '/posts/$postId': typeof DashboardPostsPostIdRouteRouteWithChildren
  '/products/new': typeof DashboardProductsNewRouteRoute
  '/products/order': typeof DashboardProductsOrderRouteRoute
  '/users/$id': typeof DashboardUsersIdRouteRoute
  '/about/': typeof DashboardAboutIndexRoute
  '/analytics': typeof DashboardAnalyticsIndexRoute
  '/categories': typeof DashboardCategoriesIndexRoute
  '/orders': typeof DashboardOrdersIndexRoute
  '/posts/': typeof DashboardPostsIndexRoute
  '/products': typeof DashboardProductsIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/categories/$id/edit': typeof DashboardCategoriesIdEditRouteRoute
  '/products/$id/edit': typeof DashboardProductsIdEditRouteRoute
  '/posts/$postId/': typeof DashboardPostsPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/constants': typeof DashboardConstantsRouteRoute
  '/': typeof DashboardIndexRoute
  '/categories/new': typeof DashboardCategoriesNewRouteRoute
  '/categories/order': typeof DashboardCategoriesOrderRouteRoute
  '/orders/$id': typeof DashboardOrdersIdRouteRoute
  '/products/new': typeof DashboardProductsNewRouteRoute
  '/products/order': typeof DashboardProductsOrderRouteRoute
  '/users/$id': typeof DashboardUsersIdRouteRoute
  '/about': typeof DashboardAboutIndexRoute
  '/analytics': typeof DashboardAnalyticsIndexRoute
  '/categories': typeof DashboardCategoriesIndexRoute
  '/orders': typeof DashboardOrdersIndexRoute
  '/posts': typeof DashboardPostsIndexRoute
  '/products': typeof DashboardProductsIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/categories/$id/edit': typeof DashboardCategoriesIdEditRouteRoute
  '/products/$id/edit': typeof DashboardProductsIdEditRouteRoute
  '/posts/$postId': typeof DashboardPostsPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_dashboard/about': typeof DashboardAboutRouteRouteWithChildren
  '/_dashboard/constants': typeof DashboardConstantsRouteRoute
  '/_dashboard/posts': typeof DashboardPostsRouteRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/categories/new': typeof DashboardCategoriesNewRouteRoute
  '/_dashboard/categories/order': typeof DashboardCategoriesOrderRouteRoute
  '/_dashboard/orders/$id': typeof DashboardOrdersIdRouteRoute
  '/_dashboard/posts/$postId': typeof DashboardPostsPostIdRouteRouteWithChildren
  '/_dashboard/products/new': typeof DashboardProductsNewRouteRoute
  '/_dashboard/products/order': typeof DashboardProductsOrderRouteRoute
  '/_dashboard/users/$id': typeof DashboardUsersIdRouteRoute
  '/_dashboard/about/': typeof DashboardAboutIndexRoute
  '/_dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/_dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/_dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/_dashboard/posts/': typeof DashboardPostsIndexRoute
  '/_dashboard/products/': typeof DashboardProductsIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_dashboard/categories/$id/edit': typeof DashboardCategoriesIdEditRouteRoute
  '/_dashboard/products/$id/edit': typeof DashboardProductsIdEditRouteRoute
  '/_dashboard/posts/$postId/': typeof DashboardPostsPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/constants'
    | '/posts'
    | '/'
    | '/categories/new'
    | '/categories/order'
    | '/orders/$id'
    | '/posts/$postId'
    | '/products/new'
    | '/products/order'
    | '/users/$id'
    | '/about/'
    | '/analytics'
    | '/categories'
    | '/orders'
    | '/posts/'
    | '/products'
    | '/users'
    | '/login'
    | '/categories/$id/edit'
    | '/products/$id/edit'
    | '/posts/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/constants'
    | '/'
    | '/categories/new'
    | '/categories/order'
    | '/orders/$id'
    | '/products/new'
    | '/products/order'
    | '/users/$id'
    | '/about'
    | '/analytics'
    | '/categories'
    | '/orders'
    | '/posts'
    | '/products'
    | '/users'
    | '/login'
    | '/categories/$id/edit'
    | '/products/$id/edit'
    | '/posts/$postId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_public'
    | '/_dashboard/about'
    | '/_dashboard/constants'
    | '/_dashboard/posts'
    | '/_dashboard/'
    | '/_dashboard/categories/new'
    | '/_dashboard/categories/order'
    | '/_dashboard/orders/$id'
    | '/_dashboard/posts/$postId'
    | '/_dashboard/products/new'
    | '/_dashboard/products/order'
    | '/_dashboard/users/$id'
    | '/_dashboard/about/'
    | '/_dashboard/analytics/'
    | '/_dashboard/categories/'
    | '/_dashboard/orders/'
    | '/_dashboard/posts/'
    | '/_dashboard/products/'
    | '/_dashboard/users/'
    | '/_public/login/'
    | '/_dashboard/categories/$id/edit'
    | '/_dashboard/products/$id/edit'
    | '/_dashboard/posts/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/posts': {
      id: '/_dashboard/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof DashboardPostsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/constants': {
      id: '/_dashboard/constants'
      path: '/constants'
      fullPath: '/constants'
      preLoaderRoute: typeof DashboardConstantsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/about': {
      id: '/_dashboard/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DashboardAboutRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products/': {
      id: '/_dashboard/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/posts/': {
      id: '/_dashboard/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardPostsRouteRoute
    }
    '/_dashboard/orders/': {
      id: '/_dashboard/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/categories/': {
      id: '/_dashboard/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/analytics/': {
      id: '/_dashboard/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/about/': {
      id: '/_dashboard/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof DashboardAboutIndexRouteImport
      parentRoute: typeof DashboardAboutRouteRoute
    }
    '/_dashboard/users/$id': {
      id: '/_dashboard/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof DashboardUsersIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products/order': {
      id: '/_dashboard/products/order'
      path: '/products/order'
      fullPath: '/products/order'
      preLoaderRoute: typeof DashboardProductsOrderRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products/new': {
      id: '/_dashboard/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/posts/$postId': {
      id: '/_dashboard/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof DashboardPostsPostIdRouteRouteImport
      parentRoute: typeof DashboardPostsRouteRoute
    }
    '/_dashboard/orders/$id': {
      id: '/_dashboard/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof DashboardOrdersIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/categories/order': {
      id: '/_dashboard/categories/order'
      path: '/categories/order'
      fullPath: '/categories/order'
      preLoaderRoute: typeof DashboardCategoriesOrderRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/categories/new': {
      id: '/_dashboard/categories/new'
      path: '/categories/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof DashboardCategoriesNewRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/posts/$postId/': {
      id: '/_dashboard/posts/$postId/'
      path: '/'
      fullPath: '/posts/$postId/'
      preLoaderRoute: typeof DashboardPostsPostIdIndexRouteImport
      parentRoute: typeof DashboardPostsPostIdRouteRoute
    }
    '/_dashboard/products/$id/edit': {
      id: '/_dashboard/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof DashboardProductsIdEditRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/categories/$id/edit': {
      id: '/_dashboard/categories/$id/edit'
      path: '/categories/$id/edit'
      fullPath: '/categories/$id/edit'
      preLoaderRoute: typeof DashboardCategoriesIdEditRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardAboutRouteRouteChildren {
  DashboardAboutIndexRoute: typeof DashboardAboutIndexRoute
}

const DashboardAboutRouteRouteChildren: DashboardAboutRouteRouteChildren = {
  DashboardAboutIndexRoute: DashboardAboutIndexRoute,
}

const DashboardAboutRouteRouteWithChildren =
  DashboardAboutRouteRoute._addFileChildren(DashboardAboutRouteRouteChildren)

interface DashboardPostsPostIdRouteRouteChildren {
  DashboardPostsPostIdIndexRoute: typeof DashboardPostsPostIdIndexRoute
}

const DashboardPostsPostIdRouteRouteChildren: DashboardPostsPostIdRouteRouteChildren =
  {
    DashboardPostsPostIdIndexRoute: DashboardPostsPostIdIndexRoute,
  }

const DashboardPostsPostIdRouteRouteWithChildren =
  DashboardPostsPostIdRouteRoute._addFileChildren(
    DashboardPostsPostIdRouteRouteChildren,
  )

interface DashboardPostsRouteRouteChildren {
  DashboardPostsPostIdRouteRoute: typeof DashboardPostsPostIdRouteRouteWithChildren
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
}

const DashboardPostsRouteRouteChildren: DashboardPostsRouteRouteChildren = {
  DashboardPostsPostIdRouteRoute: DashboardPostsPostIdRouteRouteWithChildren,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
}

const DashboardPostsRouteRouteWithChildren =
  DashboardPostsRouteRoute._addFileChildren(DashboardPostsRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAboutRouteRoute: typeof DashboardAboutRouteRouteWithChildren
  DashboardConstantsRouteRoute: typeof DashboardConstantsRouteRoute
  DashboardPostsRouteRoute: typeof DashboardPostsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCategoriesNewRouteRoute: typeof DashboardCategoriesNewRouteRoute
  DashboardCategoriesOrderRouteRoute: typeof DashboardCategoriesOrderRouteRoute
  DashboardOrdersIdRouteRoute: typeof DashboardOrdersIdRouteRoute
  DashboardProductsNewRouteRoute: typeof DashboardProductsNewRouteRoute
  DashboardProductsOrderRouteRoute: typeof DashboardProductsOrderRouteRoute
  DashboardUsersIdRouteRoute: typeof DashboardUsersIdRouteRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardCategoriesIdEditRouteRoute: typeof DashboardCategoriesIdEditRouteRoute
  DashboardProductsIdEditRouteRoute: typeof DashboardProductsIdEditRouteRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAboutRouteRoute: DashboardAboutRouteRouteWithChildren,
  DashboardConstantsRouteRoute: DashboardConstantsRouteRoute,
  DashboardPostsRouteRoute: DashboardPostsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCategoriesNewRouteRoute: DashboardCategoriesNewRouteRoute,
  DashboardCategoriesOrderRouteRoute: DashboardCategoriesOrderRouteRoute,
  DashboardOrdersIdRouteRoute: DashboardOrdersIdRouteRoute,
  DashboardProductsNewRouteRoute: DashboardProductsNewRouteRoute,
  DashboardProductsOrderRouteRoute: DashboardProductsOrderRouteRoute,
  DashboardUsersIdRouteRoute: DashboardUsersIdRouteRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardCategoriesIdEditRouteRoute: DashboardCategoriesIdEditRouteRoute,
  DashboardProductsIdEditRouteRoute: DashboardProductsIdEditRouteRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
